services:
  backend:
    image: teerthraj77/backend:latest
    container_name: backend
    restart: always
    environment:
      - ALLOWED_HOSTS=*
    expose:
      - "8000"

  frontend:
    image: teerthraj77/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

